### ISSUE TITLE
How do you manage multi-tenant- I.e. Store permitted clients

### ISSUE THREAD

**Issue by countrdd** [sabinadams/nestjs-prisma-module#34]
In the documentation, you talk about passing x-tenant-id in from a drop down list, where would you store such a list for multi-tenancy?

Would you need to have a master database that only systems admins could access to add and remove tenants?

**Comment by sabinadams** [comment]
The idea here is that you would have multiple identical databases named after the tenant. Say you have a white-labeled e-commerce and 3 companies using it. You would have 3 companies:

1. Company1
2. Company2
3. Company3

This means you'd have three databases, say they're called:

1. company-1
2. company-2
3. company-3

If Company2 accesses the API, they would pass `x-tenant-id=company-2` in their header to get the correct database.
